name 'dsahni-gh-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dsahni-gh-cookbook'
long_description 'Installs/Configures dsahni-gh-cookbook'
version '0.1.2'
